### ISSUE TITLE
Any plan to came back to Indonesia? If yes, when?

### ISSUE THREAD

**Issue by anggiaj** [ariya/ama#1]
Dear Mr. Ariya Hidayat,

Selamat 'pagi', do you have any plan to came back to Indonesia? If yes, when? 

Terimakasih.

**Comment by ariya** [comment]
Hi @anggiaj!

It's rather to predict the future :smile: Since I still have so much to learn, for the near future I plan to stay where I'm staying right now so I can continue doing what I'm doing right now.

Thank you!

**Comment by anggiaj** [comment]
:+1: thank you

**Comment by dermatobia** [comment]
omigod. i was googling about issues with my js unit tests, and long story short, i came across this. 
saya baru tau ariya of the phantomjs ini orang indo, lol. 
now im a fan :D 
that's awesome, sir :+1:
