### ISSUE TITLE
Who is the fairest glib/gtk/gdk haxor you have ever met?

### ISSUE THREAD

**Issue by sirspudd** [ariya/ama#11]
Who is the fairest glib/gtk/gdk haxor you ever met?

**Comment by ariya** [comment]
Easy, it's ***\* (the name is redacted to protect the innocence).

**Comment by sirspudd** [comment]
I think you are missing 2 asterisks

**Comment by ariya** [comment]
The number of asterisks have been reduced to protect the innocence.
