### ISSUE TITLE
When did you started coding ? 

### ISSUE THREAD

**Issue by CodeDotJS** [ariya/ama#12]
We'd love to know if you tell us how you learned JavaScript.

**Comment by ariya** [comment]
For a very early start of my programming experience, see #2.

My encounter with JavaScript was a different:
- I finished school, moved to Oslo (Norway), worked for Trolltech (acquired by Nokia)
- There I worked on QtWebKit, thus my first contact with WebKit and web stack
- When debugging QtWebKit, often I needed to write HTML, CSS, and JavaScript

Doesn't it smell like an accident? :smiley:

**Comment by CodeDotJS** [comment]
Yes, it smell little like an accident :smile: 
I'd say, a great accident. 

Thanks for answering my question.
