### ISSUE TITLE
How do you feel about the changes in your role at your work?

### ISSUE THREAD

**Issue by jessearmand** [ariya/ama#14]
I have noticed that you're no longer just a software engineer, how does that feel? What kind of motivations that you have in this new role?

Also, if you don't mind answering, what was your day-to-day work looks like at the moment, compared to when you were intensively coding up something.

**Comment by ariya** [comment]
In a way, I am still an engineer. I have the responsibility to make sure that our engineering organization reaches its maximum potential, given the current constraints and where we are heading (there are many subtle details about it, but perhaps it's a subject of discussion some other time). As for the motivations, there is nothing secret about it: whatever it takes to ensure the success of the company.

My day-to-day activity? Lots of 1:1 obviously,  a few architecture review here and there, 
some coordination discussions (whether it's scheduled or ad-hoc/hallway-ish). Occasionally, the opportunity presents itself and don't be surprised to find me helping with issue triaging or code review!
