### ISSUE TITLE
Would the web development ever have a compiler, or is it a bad idea?

### ISSUE THREAD

**Issue by jessearmand** [ariya/ama#15]

**Comment by ariya** [comment]
If we think of a web (and its browser) as a platform, then yes, it is likely inevitable that a comprehensive set of tooling is necessary to build and maintain an application targeting the web. I would not only include a compiler in this context. Basically, any tools that make your development process humanly manageable will be more and more needed, up to a point where you can't avoid it anymore.

It is often the case that we don't produce the vector data for an SVG file by hand. Soon, writing a shader for your WebGL-visualization is hard to do without an additional helper tool. It is true that as of today, you can still rely on a text editor and write vanilla HTML/CSS/JavaScript by hand to construct a web site. However, at some point, it is questionable whether doing so is practical or not.

Is it a bad thing? Maybe. But we can also look it from a different perspective: it is just the evolution of the platform, the ecosystem, the community, and last but least, the tooling.

Thank you @jessearmand!
