### ISSUE TITLE
What are the three most underrated/overlooked open source projects?

### ISSUE THREAD

**Issue by newworldorder** [ariya/ama#20]

**Comment by ariya** [comment]
### Free Pascal

[Pascal](https://en.wikipedia.org/wiki/Pascal_%28programming_language%29) is (still) an excellent choice to teach programming. **Free Pascal** (web site: [freepascal.org](http://www.freepascal.org/)) has been in the development, in various forms, for the last 20 years. There is no sign that it is going to stop anytime soon, the [roadmap](http://freepascal.org/future.var) includes things such as LLVM target. This GPL-ed Pascal compiler, written in Pascal and compiled by itself,  [supports](https://en.wikipedia.org/wiki/Free_Pascal#Targets) many different systems, from 16-bit DOS to the latest iOS running 64-bit ARM CPU. With the companion projects such as the full-featured [Lazarus](https://en.wikipedia.org/wiki/Lazarus_%28IDE%29) and a rich [visual component library](https://en.wikipedia.org/wiki/Free_Component_Library), the Free Pascal ecosystem offers a one-stopping solution for everything from a coding tutorial for kids to a professional Windows application.

### Apache Traffic Server

The origin of **Apache Traffic Server** (web site: [trafficserver.apache.org](http://trafficserver.apache.org/)) can be traced back to the early days of [Inktomi](https://en.wikipedia.org/wiki/Inktomi). Being battle-hardened by processing the web traffic at the scale of Yahoo! (who acquired Inktomi), ATS enjoys a superb reputation as a [high-performance](http://conferences.oreilly.com/oscon/oscon2014/public/schedule/detail/34116),  [versatile](http://trafficserver.readthedocs.org/en/6.0.x/admin/configuring-cache.en.html) [caching proxy](http://trafficserver.readthedocs.org/en/6.0.x/admin/http-proxy-caching.en.html) (forward and reverse). [Donated](http://trafficserver.apache.org/acknowledgements.html) to Apache Foundation by Yahoo!, ATS is open-source and [developed](https://git-wip-us.apache.org/repos/asf?p=trafficserver.git) in the open. Specification compliant? Of course. Security features? You bet, ATS is [ahead](https://istlsfastyet.com/#server-performance) of the pack.

### Fossil

My shortest characterization of **Fossil**, (web site: [fossil-scm.org](http://www.fossil-scm.org/)), is usually very easy: Git on steroid. Not only you have the entire code repository and its history, you can also carry the [issue tracker](https://www.fossil-scm.org/fossil/doc/trunk/www/bugtheory.wiki) and the [wiki pages](https://www.fossil-scm.org/fossil/md_rules) whereever you go. Forget about `.git` directory, everything is packed in [a single file](https://www.fossil-scm.org/fossil/doc/trunk/www/fileformat.wiki) (with built-in [integrity self-check](https://www.fossil-scm.org/fossil/doc/trunk/www/selfcheck.wiki)) and therefore sync-ing with Google Drive/Dropbox/Box/ownCloud is trivial. Actively developed in the last 10 years, you could enjoy everything that it offers in a self-contained [executable](http://www.fossil-scm.org/download.html) (with near-zero dependencies) weighing less than today's average web page. Make no mistake: despite its killer features, Fossil is blazing fast.

**Comment by newworldorder** [comment]
Nice...looks like I have some homework to do on these projects--thanks!
