### ISSUE TITLE
how can we promote "javascript for everything" 

### ISSUE THREAD

**Issue by kuldeepkeshwar** [ariya/ama#23]

**Comment by ariya** [comment]
Hi @kuldeepkeshwar!

I'm not sure what you mean by "for everything" in this context. If it is about making JavaScript as the choice of programming language/environment for building literally _everything_, I think we all want to pause and think about it. There are likely cases where JavaScript is not the best tool and therefore it is counterproductive to push it.

If JavaScript is a suitable choice, then what we could do is to demonstrate it that yes, it is attractive to use JavaScript for that particular case. This could be anything from building a few prototypes, starting a community around it, writing documentation/tutorial/guides, etc.

In fact, if you look carefully, that is almost a universal way to promote a technology stack (whether it is JavaScript, other languages, other platforms, etc): **prove the values** that it brings to the users.

Thank you!
