### ISSUE TITLE
what do you think of front-end logging ?

### ISSUE THREAD

**Issue by kuldeepkeshwar** [ariya/ama#25]
considering the below points
- what information should be logged 
- pushing log information to server-side( instant or queued)
- performance
- handling in production (dealing with minified scripts)

**Comment by ariya** [comment]
Hi @kuldeepkeshwar! Consider that I never built any production web site, likely I'm not qualified to give a truly valuable advice for this situation.

You may want to convince @benvinegar to run his own AMA. I am very familiar with his expertise from our previous time together at [Shape Security](https://www.shapesecurity.com/). In addition, consider his experience with [Disqus](https://disqus.com/) and now [Sentry](https://www.getsentry.com/), I'm sure his recommendations will be worth its weight in gold :smile_cat: 

Thank you!

**Comment by kuldeepkeshwar** [comment]
Awesome, thanks!! for the reference
