### ISSUE TITLE
What are your favorite books?

### ISSUE THREAD

**Issue by dnkolegov** [ariya/ama#27]
[Here](https://github.com/ariya/ama/issues/8) you tell that reading helps to relax. 
What are your favorite books?
What are you reading now? 
Thanks.

**Comment by ariya** [comment]
Hi @dnkolegov,

It will be challenging to produce the favorite list from every single book I ever read. Thus, I will try to compile it from what I enjoyed reading in the last few years. In fact, glancing at my physical book shelf and my e-book collections, I can tell you the following.

Some weeks ago I finished [The Martians](https://www.goodreads.com/book/show/18007564-the-martian) (Andy Weir). I believe it was around the time when the movie was out. I was not disappointed by the wide screen adaptation, but I still like the book much better. A similar case is [The Man in the High Castle](https://www.goodreads.com/book/show/216363.The_Man_in_the_High_Castle) (Philip K. Dick), an old book that caught my attention during Amazon promotion of its TV series with the same name. While I do like the series, I think the book is much more fascinating.

Looks like I also had some fun re-reading a few books written by [Robert Ludlum](https://www.goodreads.com/author/show/5293.Robert_Ludlum), [Ken Follett](https://www.goodreads.com/author/show/3447.Ken_Follett), [Paulo Coelho](https://www.goodreads.com/author/show/566.Paulo_Coelho), and [Orson Scott Card](https://www.goodreads.com/author/show/589.Orson_Scott_Card).

On the non-fiction part of the shelf, there are the usual suspects:
- [Built to Last](http://www.goodreads.com/book/show/4122.Built_to_Last) (Jim Collins, Jerry I. Porras)
- [The Hard Thing About Hard Things](http://www.goodreads.com/book/show/18176747-the-hard-thing-about-hard-things) (Ben Horowitz)
- [Drive](http://www.goodreads.com/book/show/6452796-drive) (Daniel H. Pink )
- [The Lean Startup](http://www.goodreads.com/book/show/10127019-the-lean-startup) (Eric Ries)
- [How Google Works](http://www.goodreads.com/book/show/23158207-how-google-works) (Eric Schmidt, Jonathan Rosenberg).

In addition, I also enjoy:
- [Coders at Work](http://www.goodreads.com/book/show/6713575-coders-at-work) (Peter Seibel)
- [The Alliance](https://www.goodreads.com/book/show/20763746-the-alliance) (Reid Hoffman, et al.)
- [Linchpin](https://www.goodreads.com/book/show/7155145-linchpin) (Seth Godin)
- [Beyond Office Politics](http://www.goodreads.com/book/show/15840574-beyond-office-politics) (Linda Sommer)
- [Starts with Why](https://www.goodreads.com/book/show/7108725-start-with-why) (Simon Sinek)

And finally, what I'm reading right now:
- [Crucial Conversations](http://www.goodreads.com/book/show/15014.Crucial_Conversations) (Kerry Patterson, et al.)
- [Extreme Ownership](http://www.goodreads.com/book/show/23848190-extreme-ownership) (Jocko Willink, Leif Babin)
- [Primed to Perform](http://www.goodreads.com/book/show/24585389-primed-to-perform) (Neel Doshi, Lindsay McGregor)

Thank you!

**Comment by dnkolegov** [comment]
Very interesting and useful.
Thanks.
