### ISSUE TITLE
How do you start your work day?

### ISSUE THREAD

**Issue by sindresorhus** [ariya/ama#4]

**Comment by ariya** [comment]
Rather predictable:
- Wake up early. I always try to be as early as possible (without sacrificing too much sleep)
- Look at my calendar for the day and for the rest of week, come up with a plan
- Kids time: wake up, breakfast, getting ready, school drop off
- Arrive at my office before 9 am, get my morning dose of fruit and caffeine (tea/coffee)

**Comment by developit** [comment]
No commute?

**Comment by ariya** [comment]
As of now I live in Mountain View and I also work in Mountain View. Thus, the commute is rather short.

Still, that short commute somehow feels futuristic since I can spot up to 3 Google self-driving cars in one morning :smile:
