### ISSUE TITLE
Adobe Analytics S.Code/Datalayer auditing & automation solution via page crawl & scrape

### ISSUE THREAD

**Issue by thesmarthomeninja** [ariya/ama#40]
**Three Questions Below**
First off, let me say that you are truly a marvel, gem and a ninja in disguise!  Words cannot express the depth and multitude of the work that you've done and accomplished to make other's lives less complex.  This is ironically the reason I am here.  I had a few questions for you. My deepest apologies for not being succinct in my first edit!

**1) Not so fun Question:**
Is there a solution out there for auditing Adobe Analytics variables on the pages of my website.  In example- literally scraping Adobe Analyitcs code by page/page template level to somehow use this for verification/auditing/quality purposes?  If phantom is inappropriate for this, do you know of any direction or recommendations on where to go and seek more counsel or information on this area of work?  

**2) Fun Question:**  What brought you to be passionate about software engineering?  What made the man beind the golden code come forth and drive him to code?

**3) Last Question:**  What is the one thing/work/hobby that has given you the most purpose and meaning in your life that you can think of?  Or just one thing in general, whether kids, a project you did or a mentor/relative.

Best Regards and Admirations,
**-Kalen**

**Comment by thesmarthomeninja** [comment]
Take your time on this if you are busy and have little bandwidth to support my questions and feel free to let me know if you have any directions or ideas of where I can go to seek the solutions for the first question as the other two questions I am just curious about myself as you are eons ahead of what most would consider a very impressive level of achievements and work!  

Very curious to get any detail on "what makes your engine turn," as they say!

**Comment by ariya** [comment]
For #1, please use the usual channel to get support help on PhantomJS.

For the other two, do you have anything specific in mind? Do some [other questions](https://github.com/ariya/ama/issues?q=is%3Aissue+is%3Aclosed) which have been answered cover it?
