### ISSUE TITLE
How can we make PhantomJS 2.5 beta running on 32-bits machine?

### ISSUE THREAD

**Issue by alinoson** [ariya/ama#41]
Hi Ariya,
I m currently using phantomJS 2.5 Beta and the version i got from the following repository 'https://bitbucket.org/ariya/phantomjs/downloads/' does not work on 32 bit machine?  I tried to compile myself a 32bit version from the source i downloaded from Github but i did not succeed.
Can you please help me to generate a 32bit version or is there any steps i can follow to generate it ?

Thank you very much for your precious help.
Alinoson

**Comment by ariya** [comment]
Please use the usual channel to get help on PhantomJS support. Thanks!
