### ISSUE TITLE
PhantomJS and HTTPS proxy 

### ISSUE THREAD

**Issue by instagramlover** [ariya/ama#42]
i have an HTTPS proxy :
Here is the proxy with login info:

https://6d2a7d7f9d78558032874ec057e55b07af9ba311:39D56662E83CC3A0CCBA99E3DB331DA3D4201EAA641FB5889F2C22010B8620D9@us.opera-proxy.net:443

i can us it with curl with no problem , how can i be able to use it with pantomjs ?

**Comment by ariya** [comment]
Please use the usual channel for PhantomJS support. Thanks!
