### ISSUE TITLE
what should i learn about javascript ?

### ISSUE THREAD

**Issue by blackinitial** [ariya/ama#47]
Hi, Mr. Ariya Hidayat

I am new in the programming world, i have learned about html, css, and a little php. and now i learn Javascript Framework Vue JS, and react native. but but I think it's different from other languages like php.

What should i learn about javascript from scratch, to be good programmer ?

**Comment by ariya** [comment]
http://exploringjs.com/, it is very good to learn JavaScript.

**Comment by blackinitial** [comment]
Thanks a lot for your suggestion.. :)
