### ISSUE TITLE
How do you think the web will look like in 10 years?

### ISSUE THREAD

**Issue by sindresorhus** [ariya/ama#7]

**Comment by ariya** [comment]
For a start, the web needs to adapt to a wide range of new interaction modes with human. As an example, there is a likelihood that the concept of a screen, a flat opaque surface displaying some pixels, will be foreign.

Perhaps the natural #1 choice to query and discover information will be through speech. In addition, a set of contact lens projecting the visuals, i.e. the 2026 version of Google Glass, will be ubiquitous. This means, the web (and the stack behind it) needs to be ready to process information and display it in a  radically differen way!

It's going to be exciting :smile: 

Thank you!!
